# Generated by Django 6.0.3 on 2026-03-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("default_branch", models.CharField(max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "group_name"), name="unique_repo_name_per_group"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GitObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=40)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("blob", "Blob"),
                            ("tree", "Tree"),
                            ("commit", "Commit"),
                            ("tag", "Tag"),
                        ],
                        max_length=6,
                    ),
                ),
                ("data", models.BinaryField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_objects",
                        to="gitinator.repo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("branch", "Branch"), ("tag", "Tag")], max_length=6
                    ),
                ),
                (
                    "git_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="git_refs",
                        to="gitinator.gitobject",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_refs",
                        to="gitinator.repo",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repository", "name", "type"),
                        name="unique_git_ref_per_repo",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="gitobject",
            constraint=models.UniqueConstraint(
                fields=("repository", "sha"), name="unique_git_object_sha_per_repo"
            ),
        ),
    ]
